# Generated by Django 5.1.1 on 2024-09-25 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="item", max_length=50)),
                ("details", models.TextField(default="")),
                ("image", models.ImageField(upload_to="")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("price", models.CharField(default=0, max_length=50)),
                ("discount", models.IntegerField(default=0, max_length=3)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Food", "Food"),
                            ("Utility", "Utility"),
                            ("Optical", "Optical"),
                            ("Gadjet", "Gadjet"),
                            ("software", "software"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
