# Generated by Django 5.1.1 on 2024-09-26 04:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="items",
            options={"verbose_name_plural": "Items"},
        ),
        migrations.AlterField(
            model_name="items",
            name="details",
            field=models.TextField(
                default="",
                help_text="Detailed description of the item",
                verbose_name="Item Details",
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="discount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="items",
            name="image",
            field=models.ImageField(upload_to="item_images/"),
        ),
        migrations.AlterField(
            model_name="items",
            name="name",
            field=models.CharField(
                default="item",
                help_text="Enter the name of the item",
                max_length=500,
                verbose_name="Item Name",
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="items",
            name="type",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Utility", "Utility"),
                    ("Optical", "Optical"),
                    ("Gadget", "Gadget"),
                    ("Software", "Software"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("details", models.CharField(default="Store", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("image", models.ImageField(upload_to="store_images/")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical or region location of the store",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Food", "Food"),
                            ("Utility", "Utility"),
                            ("Optical", "Optical"),
                            ("Gadget", "Gadget"),
                            ("Software", "Software"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Is the store currently active?",
                        max_length=50,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address for contacting the store",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.EmailField(
                        blank=True,
                        help_text="Phone number for contacting the store",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="stores", to="home.category"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stores",
            },
        ),
        migrations.AddField(
            model_name="items",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="home.store",
            ),
        ),
    ]
