# Generated by Django 5.1.1 on 2024-09-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_category_alter_items_options_alter_items_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="details",
            field=models.CharField(default="Store", max_length=1000),
        ),
    ]
