# Generated by Django 5.1.1 on 2024-09-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_store_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="details",
            field=models.TextField(default="Store", max_length=1000),
        ),
    ]
