# Generated by Django 5.1.1 on 2024-09-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_store_contact_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="uploaded_by",
            field=models.CharField(default="", max_length=50),
        ),
    ]
