# Generated by Django 5.1.1 on 2024-09-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_items_uploaded_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="details",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Detailed description of the item",
                null=True,
                verbose_name="Item Details",
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="discount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
