# Generated by Django 5.1.1 on 2024-09-30 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_store_is_hidden"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the product type", max_length=50, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the store type", max_length=50, unique=True
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="store",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number for contacting the store",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="home.producttype",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stores",
                to="home.storetype",
            ),
        ),
    ]
