# Generated by Django 5.1.1 on 2024-09-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_producttype_storetype_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="type",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Utility", "Utility"),
                    ("Optical", "Optical"),
                    ("Gadget", "Gadget"),
                    ("Software", "Software"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="type",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Utility", "Utility"),
                    ("Optical", "Optical"),
                    ("Gadget", "Gadget"),
                    ("Software", "Software"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AlterField(
            model_name="store",
            name="contact_phone",
            field=models.IntegerField(
                blank=True,
                help_text="Phone number for contacting the store",
                max_length=15,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="ProductType",
        ),
        migrations.DeleteModel(
            name="StoreType",
        ),
    ]
