# Generated by Django 5.1.1 on 2024-10-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_items_type_alter_store_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="location",
            field=models.CharField(
                blank=True,
                default="Chishtian",
                help_text="Physical or region location of the store",
                max_length=50,
                null=True,
            ),
        ),
    ]
