# Generated by Django 5.1.1 on 2024-10-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_store_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="keywords",
            field=models.CharField(
                blank=True,
                help_text="Enter keywords for search separated by commas",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="items",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of items available in stock"
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="contact_phone",
            field=models.IntegerField(
                blank=True, help_text="Phone number for contacting the store", null=True
            ),
        ),
    ]
